### The basics

In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# get dimension
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# get shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
# get type
a.dtype

dtype('int64')

In [11]:
b.dtype

dtype('int64')

In [13]:
a=np.array([1,2,3],dtype='int16')
a.dtype

dtype('int16')

In [15]:
# get size
a.size

3

In [17]:
a.itemsize

2

In [19]:
# get total size
print(a.size*a.itemsize)
print(a.nbytes)

6
6


### Accessing or changing specific elements,rows,columns,etc..

In [20]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
a.shape

(2, 5)

In [24]:
# get a specific element [r,c]
print(a[1,4])
print(a[1,-1])

10
10


In [25]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5])

In [26]:
# get a specific column
a[:,2]

array([3, 8])

In [31]:
# [startindex:endindex:stepsize]
a[0,1:3]

array([2, 3])

In [32]:
a[0,1:4]

array([2, 3, 4])

In [33]:
a[0,1:4:2]

array([2, 4])

In [36]:
# change a element
a[1,2]=20
print(a)

[[ 1  2  3  4  5]
 [ 6  7 20  9 10]]


In [37]:
a[0,:]=5
print(a)

[[ 5  5  5  5  5]
 [ 6  7 20  9 10]]


In [39]:
# 3d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# get specific element
print(b[0,1,1])

4


In [45]:
# replace
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Intializing different types of arrays

In [48]:
# all 0s matrix
print(np.zeros(5))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
# all 1s matrix
print(np.ones((2,3)))
print(np.ones((2,3),dtype='int32'))

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [51]:
# any other number
print(np.full((2,2),100))

[[100 100]
 [100 100]]


In [54]:
# any other number (full_like)
print(np.full_like(a,2))
print(np.full(a.shape,2))

[[2 2 2 2 2]
 [2 2 2 2 2]]
[[2 2 2 2 2]
 [2 2 2 2 2]]


In [55]:
# random decimal numbers
print(np.random.rand(4,2))

[[0.01505507 0.49065413]
 [0.1613677  0.73906811]
 [0.19095601 0.27982341]
 [0.59820024 0.68875353]]


In [56]:
print(np.random.random_sample(a.shape))

[[0.95026952 0.1544092  0.98102757 0.50116777 0.70809494]
 [0.06614524 0.16539778 0.75071461 0.53671408 0.42420027]]


In [57]:
# random integer values
print(np.random.randint(7,size=(2,2)))

[[6 3]
 [0 1]]


In [58]:
print(np.random.randint(2,5,size=(2,2)))

[[2 3]
 [2 4]]


In [59]:
# identity matrix
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


In [65]:
# repeat the elements of an array
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [66]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [76]:
# practice qn (5,5) i.e., 1 1 1 1 1, 1 0 0 0 1, 1 0 9 0 1, 1 0 0 0 1, 1 1 1 1 1
output=np.ones((5,5),dtype='int32')
z=np.zeros((3,3),dtype='int32')
z[1,1]=9
output[1:4,1:4]=z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Copying arrays

In [78]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [79]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [81]:
a=np.array([1,2,3,4])
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [83]:
b=np.array([1,0,1,0])
print(a+b)
print(a**2)

[2 2 4 4]
[ 1  4  9 16]


In [84]:
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


### Linear algebra

In [86]:
a=np.full((2,3),2)
b=np.full((3,2),1)
print(a)
print(b)
print(np.matmul(a,b))

[[2 2 2]
 [2 2 2]]
[[1 1]
 [1 1]
 [1 1]]
[[6 6]
 [6 6]]


In [88]:
c=np.identity(3)
print(np.linalg.det(c))

1.0


### Statistics

In [90]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)
print(np.min(stats))
print(np.max(stats))
print(np.min(stats,axis=0))
print(np.min(stats,axis=1))
print(np.max(stats,axis=0))
print(np.max(stats,axis=1))
print(np.sum(stats))
print(np.sum(stats,axis=0))

[[1 2 3]
 [4 5 6]]
1
6
[1 2 3]
[1 4]
[4 5 6]
[3 6]
21
[5 7 9]


### Reorganizing arrays

In [93]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
after=before.reshape((8,1))
print(after)
after=before.reshape((4,2))
print(after)
after=before.reshape((2,2,2))
print(after)

(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [95]:
# vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [96]:
# horizontal stacking
h1=np.ones((2,4))
h2=np.zeros((2,2))
print(np.hstack([h1,h2]))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


### Miscellaneous

In [13]:
# load data from file
filedata=np.genfromtxt('data.txt',delimiter=',')
print(filedata)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


In [14]:
filedata.astype('int32')
print(filedata)
filedata=filedata.astype('int32')
print(filedata)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
# you can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [17]:
# advanced indexing and boolean masking
print(filedata>10)
print(filedata[filedata>10])

[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True]
[11 12 13 14 15 16 17 18 19 20]


In [24]:
print(np.any(filedata>10,axis=0))

True


In [25]:
print(np.all(filedata>10,axis=0))

False


In [22]:
((filedata>10)&(filedata<15))

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [23]:
(~((filedata>10)&(filedata<15)))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [32]:
# practice qn (6,5) i.e., 1 to 30
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a)
print(a[2:4,0:2])
print(a[[0,1,2,3],[1,2,3,4]])
print(a[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
